apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: event-greeter-subscriber
  namespace: knativetutorial
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: ch-event-greeter
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-greeter
