apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: event-greeter-cronjob-source
  namespace: knativetutorial
spec:
  schedule: "*/1 * * * *"
  data: '{"message": "Thanks for doing Knative Tutorial"}'
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: ch-event-greeter
