apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
  namespace: knativetutorial
spec:
  release:
    revisions: ["greeter-00002"]
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhdevelopers/greeter:0.0.1
            env:
              - name: MESSAGE_PREFIX
                value: Namaste
            livenessProbe:
              httpGet:
                path: /healthz
            readinessProbe:
              httpGet:
                path: /healthz
