apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
  namespace: knativetutorial
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhdevelopers/greeter:0.0.1
            livenessProbe:
              httpGet:
                path: /healthz
            readinessProbe:
              httpGet:
                path: /healthz
